name: MateLiveKit

options:
  deploymentTarget:
    iOS: "16.0"
  bundleIdPrefix: uk.drascom

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift
    from: 2.0.0

targets:
  MateLiveKit:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.drascom.mate.livekit
        DEVELOPMENT_TEAM: 59P494J56R
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "0.1"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Sources/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: LiveKit
        product: LiveKit
